name: Tests

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.9.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup infracost
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Capture infracost version installed
        run: |
          export INFRACOST_VERSION=$( infracost --version )
          echo 'INFRACOST_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
          infracost --version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Verify
        shell: python
        env:
          INFRACOST_VERSION_EXPECTED: "0.9.12"
        run: |
          import sys, os
          sys.exit(
              int(not os.environ["INFRACOST_VERSION_EXPECTED"] in os.environ["INFRACOST_VERSION_INSTALLED"])
          )
