name: Tests

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup infracost
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Get latest version
        run: |
          export INFRACOST_LATEST_VERSION=$(curl -s https://api.github.com/repos/infracost/infracost/releases/latest | jq -r .name )
          echo "Latest version: $INFRACOST_LATEST_VERSION"
          echo "INFRACOST_LATEST_VERSION=Infracost $INFRACOST_LATEST_VERSION" >> $GITHUB_ENV

      - name: Capture infracost version installed
        run: |
          echo "INFRACOST_VERSION_INSTALLED=$( infracost --version )" >> $GITHUB_ENV
      - name: Verify
        shell: python
        run: |
          import sys, os
          sys.exit(
              int(not os.environ["INFRACOST_LATEST_VERSION"] == os.environ["INFRACOST_VERSION_INSTALLED"])
          )
